### PR TITLE
Implement EKFiber using libmill coroutines instead of GCD semaphores

### LINKED ISSUE #19: Deadlock when repeatedly calling operators implemented in terms of EKEnumerator in a tight loop
`EKFiber` is implemented in a fairly heavyweight fashion in terms of `NSOperationQueue` and GCD semaphores. When a lot of fibers are created and completed within a tight loop, eventually a limit is reached where the system deadlocks. There are usually ~65 blocked operations when the deadlock occurs.

I've done a bunch of refactoring of `EKFiber` and its callers in [this branch](https://github.com/sharplet/EnumeratorKit/tree/deadlock). Even moving from the current design (one `NSOperationQueue` per `EKFiber`) to a much simplified one (a single global `NSOperationQueue` for all `EKFiber` instances) doesn't resolve the problem. So the deadlock seems to be caused by the way semaphores are used to suspend execution.

The real solution is likely going to be switching to a lighter-weight concurrency model based on coroutines. Here are some possibilities I've found after some quick research:

- [libtask](https://code.google.com/p/libtask/)
- [libconcurrency](https://code.google.com/p/libconcurrency/)
- [cloudwu/coroutine](https://github.com/cloudwu/coroutine)
- Mike Ash's [MAGenerator](https://github.com/mikeash/magenerator) ([original article](https://mikeash.com/pyblog/friday-qa-2009-10-30-generators-in-objective-c.html))

### PR DESCRIPTION
**Pull request by sharplet**
Fixes #19.

Internally, `EKFiber` now executes its block on a coroutine instead of a GCD target queue, and uses channels instead of semaphores for communication across coroutine boundaries.

`EKFiberSpec` now includes an example that produces 10000 concurrent coroutines, which performs very well! Under the old implementation, just 61 fibers would grind the process to a halt on my machine.

### CODE REVIEW

**Comment by sharplet** [comment]
Hmm, looks like because CocoaPods has no awareness of the workspace configuration, it doesn't now how to find or build libmill. Probably going to need to make a reasonable change to the podspec to get that to work. :disappointed:

**Comment by sharplet** [comment]
If anyone's interested in testing this via CocoaPods now, you should be able to use

``` ruby
pod "EnumeratorKit", git: "https://github.com/sharplet/EnumeratorKit.git", branch: "libmill"
```

**Comment by sharplet** [comment]
So `pod lib lint` doesn't seem to respect the use of `preserve_paths` in the podspec. I've opened https://github.com/CocoaPods/CocoaPods/issues/4607.

**Comment by alaroldai** [comment]
Dude, libmill looks awesome! I can't believe I'd never heard of it before!

**Comment by sharplet** [comment]
I know, right? :sparkles:

**Comment by sharplet** [comment]
Closing this as stale for now, but I'll leave the branch around for posterity.

**Pull request closed without merging**
